coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 1%
    patch:
      default:
        target: 80%
        threshold: 1%

flags:
  unittests:
    paths:
      - src
    carryforward: true

ignore:
  - "dist/**/*"
  - "coverage/**/*"
  - "**/*.d.ts"
  - "vite.config.ts"
  - "vitest.config.ts"
  - "tests/**/*"
  - "setup.py"
  - "**/*.test.js"
  - "**/*.test.tsx"
  - "**/*.spec.js"
  - "**/*.spec.tsx"

comment:
  layout: "reach, diff, flags, files, components"
  behavior: default
  require_changes: false
  show_carryforward_flags: true

component_management:
  individual_components:
    - component_id: "core"
      paths:
        - src/components/
    - component_id: "hooks"
      paths:
        - src/hooks/
    - component_id: "utils"
      paths:
        - src/utils/